(() => {
  "use strict";
  const DATA=window.SCANS_DATA;if(!DATA)return;
  const slug=document.body.dataset.collection,collection=DATA.collections.find(item=>item.slug===slug);
  if(!collection){document.body.innerHTML='<p class="noscript">Collection not found. <a href="../index.html">Return to Scans Archive</a>.</p>';return}
  const copy={
    en:{mainArchive:"MAIN ARCHIVE ↗",backToScans:"SCANS ARCHIVE",galleries:"GALLERIES",scans:"SCANS",updated:"UPDATED",searchGalleries:"SEARCH GALLERIES...",sort:"SORT",sourceOrder:"SOURCE ORDER",newest:"NEWEST",largest:"MOST SCANS",openSource:"OPEN SOURCE FOLDER",noResults:"NO GALLERIES FOUND",scansArchive:"SCANS ARCHIVE",backTop:"BACK TO TOP ↑",openFolder:"OPEN FOLDER",downloadNote:"USE “DOWNLOAD ↓” BELOW EACH SCAN TO SAVE THE ORIGINAL FILE.",openGallery:"OPEN GALLERY",groups:"SECTIONS",results:"GALLERIES",view:"VIEW",download:"DOWNLOAD",pdf:"PDF VERSION"},
    ko:{mainArchive:"메인 아카이브 ↗",backToScans:"스캔 아카이브",galleries:"갤러리",scans:"스캔",updated:"업데이트",searchGalleries:"갤러리 검색...",sort:"정렬",sourceOrder:"원본 순서",newest:"최신순",largest:"스캔 많은 순",openSource:"원본 폴더 열기",noResults:"갤러리를 찾을 수 없습니다",scansArchive:"스캔 아카이브",backTop:"맨 위로 ↑",openFolder:"폴더 열기",downloadNote:"각 스캔 아래의 ‘다운로드 ↓’를 눌러 원본 파일을 저장할 수 있습니다.",openGallery:"갤러리 열기",groups:"섹션",results:"갤러리",view:"보기",download:"다운로드",pdf:"PDF 버전"}
  };
  const state={lang:localStorage.getItem("tbzScansLang")==="ko"?"ko":"en",query:"",sort:"source",current:null};
  const $=selector=>document.querySelector(selector),driveFolder=id=>`https://drive.google.com/drive/folders/${encodeURIComponent(id)}`,thumb=(id,width=1000)=>`https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w${width}`,view=id=>`https://drive.google.com/file/d/${encodeURIComponent(id)}/view`,download=id=>`https://drive.google.com/uc?export=download&id=${encodeURIComponent(id)}`;
  const number=value=>new Intl.NumberFormat(state.lang==="ko"?"ko-KR":"en-US").format(value||0);
  const date=value=>{if(!value)return"—";const current=new Date(value);return state.lang==="ko"?new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"2-digit",day:"2-digit"}).format(current):new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(current).toUpperCase()};
  function sortedGalleries(){const items=collection.galleries.map((gallery,index)=>({gallery,index})).filter(({gallery})=>gallery.name.toLocaleLowerCase().includes(state.query));if(state.sort==="newest")items.sort((a,b)=>(b.gallery.updatedAt||"").localeCompare(a.gallery.updatedAt||""));if(state.sort==="largest")items.sort((a,b)=>b.gallery.imageCount-a.gallery.imageCount);if(state.sort==="az")items.sort((a,b)=>a.gallery.name.localeCompare(b.gallery.name,undefined,{numeric:true}));return items}
  function galleryCard(gallery,index){
    const article=document.createElement("article");article.className="card";
    const imageButton=document.createElement("button");imageButton.className="thumb";imageButton.type="button";imageButton.dataset.open=gallery.id;imageButton.setAttribute("aria-label",`${copy[state.lang].openGallery}: ${gallery.name}`);
    if(gallery.coverId){const image=document.createElement("img");image.src=thumb(gallery.coverId);image.alt="";image.loading="lazy";image.referrerPolicy="no-referrer";imageButton.append(image)}else{const placeholder=document.createElement("span");placeholder.className="thumb-placeholder";placeholder.textContent="PDF / FOLDER";imageButton.append(placeholder)}
    const badge=document.createElement("span");badge.className="number";badge.textContent=String(index+1).padStart(2,"0");const count=document.createElement("span");count.className="photo-count";count.textContent=`${number(gallery.imageCount)} ${copy[state.lang].scans}`;imageButton.append(badge,count);
    const info=document.createElement("div");info.className="card-info";const eyebrow=document.createElement("span");eyebrow.className="eyebrow";eyebrow.textContent=`${collection.nameEn} / ${String(index+1).padStart(2,"0")}`;const title=document.createElement("h2");title.textContent=gallery.name;
    const meta=document.createElement("div");meta.className="meta";[[copy[state.lang].scans,number(gallery.imageCount)],[copy[state.lang].groups,number(gallery.groups.length)],[copy[state.lang].updated,date(gallery.updatedAt)]].forEach(([label,value])=>{const labelElement=document.createElement("span");labelElement.textContent=label;const valueElement=document.createElement("strong");valueElement.textContent=value;meta.append(labelElement,valueElement)});
    const actions=document.createElement("div");actions.className="card-actions";const openButton=document.createElement("button");openButton.type="button";openButton.dataset.open=gallery.id;openButton.textContent=`${copy[state.lang].openGallery} →`;const source=document.createElement("a");source.href=driveFolder(gallery.folderId);source.target="_blank";source.rel="noopener noreferrer";source.textContent=`${copy[state.lang].openFolder} ↗`;actions.append(openButton,source);info.append(eyebrow,title,meta,actions);article.append(imageButton,info);return article;
  }
  function renderCards(){const items=sortedGalleries(),cards=$("#cards");cards.replaceChildren();items.forEach(({gallery},index)=>cards.append(galleryCard(gallery,index)));$("#resultsCount").textContent=`${number(items.length)} ${copy[state.lang].results}`;$("#empty").hidden=items.length!==0}
  function photoCard(image){const figure=document.createElement("figure");figure.className="photo";const picture=document.createElement("img");picture.src=thumb(image.id,1600);picture.alt=image.name;picture.loading="lazy";picture.referrerPolicy="no-referrer";if(image.width&&image.height){picture.width=image.width;picture.height=image.height}const bar=document.createElement("figcaption");bar.className="photo-bar";const name=document.createElement("span");name.className="photo-name";name.title=image.name;name.textContent=image.name;const links=document.createElement("span");links.className="photo-links";const viewLink=document.createElement("a");viewLink.href=view(image.id);viewLink.target="_blank";viewLink.rel="noopener noreferrer";viewLink.textContent=`${copy[state.lang].view} ↗`;const downloadLink=document.createElement("a");downloadLink.href=download(image.id);downloadLink.target="_blank";downloadLink.rel="noopener noreferrer";downloadLink.textContent=`${copy[state.lang].download} ↓`;links.append(viewLink,downloadLink);bar.append(name,links);figure.append(picture,bar);return figure}
  function renderOpenGallery(){
    const gallery=state.current;if(!gallery)return;$("#dialogTitle").textContent=gallery.name;$("#dialogKicker").textContent=`${collection.nameEn} · ${number(gallery.imageCount)} ${copy[state.lang].scans}`;$("#dialogDrive").href=driveFolder(gallery.folderId);
    const pdfs=$("#pdfLinks");pdfs.replaceChildren();pdfs.hidden=gallery.pdfs.length===0;gallery.pdfs.forEach((pdf,index)=>{const link=document.createElement("a");link.href=view(pdf.id);link.target="_blank";link.rel="noopener noreferrer";link.textContent=`${copy[state.lang].pdf}${gallery.pdfs.length>1?` ${index+1}`:""} ↗`;pdfs.append(link)});
    const groups=$("#galleryGroups");groups.replaceChildren();gallery.groups.forEach(group=>{const section=document.createElement("section");section.className="scan-group";const heading=document.createElement("h3");heading.className="group-heading";heading.textContent=`${group.name} / ${number(group.images.length)} ${copy[state.lang].scans}`;const grid=document.createElement("div");grid.className="photo-grid";group.images.forEach(image=>grid.append(photoCard(image)));section.append(heading,grid);groups.append(section)});
  }
  function openGallery(id){state.current=collection.galleries.find(gallery=>gallery.id===id);if(!state.current)return;renderOpenGallery();$("#galleryDialog").showModal();document.body.classList.add("modal-open")}
  function applyLanguage(){const lang=copy[state.lang];document.documentElement.lang=state.lang==="ko"?"ko":"en";$("#langToggle").textContent=state.lang==="ko"?"KOR":"EN";document.querySelectorAll("[data-i18n]").forEach(element=>{element.textContent=lang[element.dataset.i18n]});document.querySelectorAll("[data-i18n-placeholder]").forEach(element=>{element.placeholder=lang[element.dataset.i18nPlaceholder]});const title=$("#collectionTitle");title.replaceChildren();const solid=document.createElement("span");solid.className="solid";solid.textContent=state.lang==="ko"?collection.nameKo:collection.nameEn;const outline=document.createElement("span");outline.className="outline";outline.textContent="SCANS";title.append(solid,outline);const length=solid.textContent.length;$(".collection-masthead").classList.toggle("title-long",length>17);$(".collection-masthead").classList.toggle("title-very-long",length>23);$("#galleryCount").textContent=number(collection.galleryCount);$("#scanCount").textContent=number(collection.imageCount);$("#updatedDate").textContent=date(collection.updatedAt);renderCards();if(state.current&&$("#galleryDialog").open)renderOpenGallery()}
  document.title=`${collection.nameEn} — Scans Archive`;$("#collectionDrive").href=driveFolder(collection.id);
  $("#search").addEventListener("input",event=>{state.query=event.target.value.trim().toLocaleLowerCase();renderCards()});$("#sortFilter").addEventListener("change",event=>{state.sort=event.target.value;renderCards()});$("#cards").addEventListener("click",event=>{const target=event.target.closest("[data-open]");if(target)openGallery(target.dataset.open)});$("#closeDialog").addEventListener("click",()=>$("#galleryDialog").close());$("#galleryDialog").addEventListener("close",()=>{document.body.classList.remove("modal-open");state.current=null;$("#galleryGroups").replaceChildren()});$("#galleryDialog").addEventListener("click",event=>{if(event.target===$("#galleryDialog"))$("#galleryDialog").close()});$("#langToggle").addEventListener("click",()=>{state.lang=state.lang==="en"?"ko":"en";localStorage.setItem("tbzScansLang",state.lang);applyLanguage()});applyLanguage();
})();
